// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIhPYWfMOWK4NmfLCRY6Ya6B4JSABbN30',
    appId: '1:971563469461:web:99fab18b18cef12b5da99c',
    messagingSenderId: '971563469461',
    projectId: 'money-1c2be',
    authDomain: 'money-1c2be.firebaseapp.com',
    storageBucket: 'money-1c2be.appspot.com',
    measurementId: 'G-8LEWDR5Y43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmQRPYmCdajgKm1lzLRNlpt8I6tXToJyo',
    appId: '1:971563469461:android:cd48e5cde9f456665da99c',
    messagingSenderId: '971563469461',
    projectId: 'money-1c2be',
    storageBucket: 'money-1c2be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuJsCWI91LQbUCMVuS5gpUqfTufaBhlcQ',
    appId: '1:971563469461:ios:ef4e6442e55c74995da99c',
    messagingSenderId: '971563469461',
    projectId: 'money-1c2be',
    storageBucket: 'money-1c2be.appspot.com',
    iosBundleId: 'com.example.abc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuJsCWI91LQbUCMVuS5gpUqfTufaBhlcQ',
    appId: '1:971563469461:ios:91b6253eb52b77b65da99c',
    messagingSenderId: '971563469461',
    projectId: 'money-1c2be',
    storageBucket: 'money-1c2be.appspot.com',
    iosBundleId: 'com.example.abc.RunnerTests',
  );
}
